DeliveryLocator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Customer Delivery Location API",
        default_version="v1",
        description="This API endpoint, avaliable at 'localhost:8000/api/v1/delivery-locations', is designed to retrieve a list of all delivery locations stored in the system. It provides access to comprehensive information about each delivery location, including its name, geographic coordinates, and additional details.",
        terms_of_service="https://https://github.com/ishanshre/GeoDjangoCLDM",
        contact=openapi.Contact(email="ishan.shrestha356@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("api/v1/", include("location.api.urls")),
    path("user/", include("account.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "api/docs/swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "api/docs/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/docs/redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(next_page="account:login"), name="logout"),
]

location/urls.py
from django.urls import path

from . import views

app_name = "location"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.LocationCreateView.as_view(), name="location_create"),
    path(
        "<slug:slug>/detail/",
        views.LocationDetailView.as_view(),
        name="location_detail",
    ),
    path(
        "<slug:slug>/delete/",
        views.LocationDeleteView.as_view(),
        name="location_delete",
    ),
    path(
        "<slug:slug>/update/",
        views.LocationUpdateView.as_view(),
        name="location_update",
    ),
]

templates/index.html
{% extends 'layout/base.html' %}
{% block title %}Home{% endblock title %}


{% block body %}
<div class="contianer">
    <div class="d-flex justify-content-center align-item-center">
        <h1 class="text-center p-5 mb-10">Customer Name: {{request.user.full_name}}</h1>
        <div class="d-flex justify-content-center align-items-center">
            <a href="{% url 'location:location_create' %}" class="btn btn-primary">Add</a>
        </div>
    </div>
    <div class="d-flex justify-content-center align-items-center">
        <div>
            <table class="table table-striped-columns table-hover">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Name</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for location in locations %}
                    <tr class="
                    {% if location.is_primary %}
                    table-active        
                    {% endif %}
                    ">
                        <td>{{forloop.counter}}</td>
                        <td>{{location.name}}{% if location.is_primary %}
                            (Default)
                            {% endif %}</td>
                        <td>{{location.location.y}}</td>
                        <td>{{location.location.x}}</td>
                        <td>
                            <a href="{{location.get_absolute_url}}" class="btn btn-secondary">Detail</a>
                            <a href="{% url 'location:location_delete' location.slug %}"
                                class="btn btn-danger">Delete</a>
                            <a href="{% url 'location:location_update' location.slug %}"
                                class="btn btn-danger">Update</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            <div class="d-flex justify-content-center align-content-center">
                {% include "layout/pagination.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock body %}