DeliveryLocator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Customer Delivery Location API",
        default_version="v1",
        description="This API endpoint, avaliable at 'localhost:8000/api/v1/delivery-locations', is designed to retrieve a list of all delivery locations stored in the system. It provides access to comprehensive information about each delivery location, including its name, geographic coordinates, and additional details.",
        terms_of_service="https://https://github.com/ishanshre/GeoDjangoCLDM",
        contact=openapi.Contact(email="ishan.shrestha356@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("api/v1/", include("location.api.urls")),
    path("user/", include("account.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "api/docs/swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "api/docs/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/docs/redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(next_page="account:login"), name="logout"),
]

location/urls.py
from django.urls import path

from . import views

app_name = "location"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.LocationCreateView.as_view(), name="location_create"),
    path(
        "<slug:slug>/detail/",
        views.LocationDetailView.as_view(),
        name="location_detail",
    ),
    path(
        "<slug:slug>/delete/",
        views.LocationDeleteView.as_view(),
        name="location_delete",
    ),
    path(
        "<slug:slug>/update/",
        views.LocationUpdateView.as_view(),
        name="location_update",
    ),
]

templates/layout/base.html
<!doctype html>
<html lang="en">
{% load leaflet_tags %}

<head>
    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
    {% endblock css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    {% include 'layout/navbar.html' %}
    {% include 'layout/messages.html' %}
    <div class="container cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        {% block body %}
        {% endblock body %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>

templates/layout/messages.html
{% if messages %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'location:index' %}">Custom Location Manager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {% if request.user.is_authenticated %}
                        @{{request.user.username}}
                        {% else %}
                        User
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:signup' %}">SignUp</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/layout/pagination.html
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}" class="page-item text-decoration-none btn btn-outline-primary">«
    Previous page</a>

{% if page_obj.number > 3 %}
<a href="?page=1" class="page-item text-decoration-none">1</a>
{% if page_obj.number > 4 %}
<span>...</span>
{% endif %}
{% endif %}
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a href="?page={{ num }}" class="page-item text-decoration-none btn btn-outline-primary">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a href="?page={{ num }}"
    class="page-item text-decoration-none">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %} <span>...</span>
        <a href="?page={{ page_obj.paginator.num_pages }}"
            class="page-item text-decoration-none btn btn-outline-primary">{{ page_obj.paginator.num_pages }}</a>
        {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %} <a
            href="?page={{ page_obj.paginator.num_pages }}"
            class="page-item text-decoration-none btn btn-outline-primary">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}

            <a href="?page={{ page_obj.next_page_number }}"
                class="page-item text-decoration-none btn btn-outline-primary">Next Page »</a>
            {% endif %}